# Generated by Django 2.2.7 on 2019-11-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photolikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photolikes',
            name='like_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
